"""Add verified column to user

Revision ID: 209a61b8ab03
Revises: 7dd1564a2568
Create Date: 2024-12-08 10:14:38.931062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209a61b8ab03'
down_revision = '7dd1564a2568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
